// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKteuhrkcd7ESbEPnHSYk0g9jl3zu9VNQ',
    appId: '1:429060196272:web:d823ff5c305bd76ce0f875',
    messagingSenderId: '429060196272',
    projectId: 'unilink-adbaa',
    authDomain: 'unilink-adbaa.firebaseapp.com',
    storageBucket: 'unilink-adbaa.firebasestorage.app',
    measurementId: 'G-W530BGHMV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMBjLmG5hDTSrzsExdw2DZF7bQSZl9p0',
    appId: '1:429060196272:android:a39fb5b4886391ede0f875',
    messagingSenderId: '429060196272',
    projectId: 'unilink-adbaa',
    storageBucket: 'unilink-adbaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFTn1A45vLWmsAs3q1_pcjS-TuEis3ZmM',
    appId: '1:429060196272:ios:43d3a3081501e07ee0f875',
    messagingSenderId: '429060196272',
    projectId: 'unilink-adbaa',
    storageBucket: 'unilink-adbaa.firebasestorage.app',
    iosClientId: '429060196272-83sbi9mrvhhd2bdipjl85siu0qcgk4jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.unilink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFTn1A45vLWmsAs3q1_pcjS-TuEis3ZmM',
    appId: '1:429060196272:ios:43d3a3081501e07ee0f875',
    messagingSenderId: '429060196272',
    projectId: 'unilink-adbaa',
    storageBucket: 'unilink-adbaa.firebasestorage.app',
    iosClientId: '429060196272-83sbi9mrvhhd2bdipjl85siu0qcgk4jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.unilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKteuhrkcd7ESbEPnHSYk0g9jl3zu9VNQ',
    appId: '1:429060196272:web:8fdf0ce8d67d396ce0f875',
    messagingSenderId: '429060196272',
    projectId: 'unilink-adbaa',
    authDomain: 'unilink-adbaa.firebaseapp.com',
    storageBucket: 'unilink-adbaa.firebasestorage.app',
    measurementId: 'G-5CS8VNWDTX',
  );

}